name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 8.12.1
          arguments: build
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
#      - name: Publish code coverage
#        uses: paambaati/codeclimate-action@v9.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
#          JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
#        with:
#          coverageCommand: make report
#          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
#      - uses: qltysh/qlty-action/coverage@main
#        with:
#          coverage-token: {{secrets.QLTY_COVERAGE_TOKEN}}
#          files: reports/coverage.xml